services:
  sandbox:
    container_name: malware-analysis-sandbox
    image: malware-sandbox:latest
    build:
      context: .
      dockerfile: sandbox/Dockerfile
    volumes:
      - ${HOME}/malware-analysis/logs:/analysis/logs
      - ${HOME}/malware-analysis/queue:/analysis/input
      - ${HOME}/malware-analysis/static-output:/analysis/static-output
    user: "1000:1000"
    network_mode: none
    mem_limit: 5g
    mem_reservation: 3g
    cpus: 2.0 
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges