version: '3.8'
services:
  sandbox:
    image: malware-sandbox:latest
    volumes:
      - $(HOME)/malware-analysis/queue:/analysis/input
      - $(HOME)/malware-analysis/static-output:/analysis/static-output
      - $(HOME)/malware-analysis/dynamic-output:/analysis/dynamic-output
    user: "1000:1000"
    network_mode: none
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges
